const {
  SUPABASE_URL,
  SUPABASE_KEY,
  CONTENTFUL_SPACE_ID,
  CONTENTFUL_PROD_ACCESS_TOKEN,
} = process.env;

module.exports = {
  SUPABASE_URL,
  SUPABASE_KEY,
  CONTENTFUL_SPACE_ID,
  CONTENTFUL_PROD_ACCESS_TOKEN,
};
